### ISSUE TITLE
TODO: replace fetching of the floor price with new method

### ISSUE THREAD

**Issue by dcts** [dcts/opensea-scraper#20]
Theres a faster way of getting floor prices I just found. When you have a collection endpoint with query params (meaning filtering is enabled), opensea exposes a `__wired__` variable to the window with a lot of information, also including the floor prices. Simply run:
```js
Object.values(__wired__.records)
  .filter(o => o.__typename === "AssetQuantityType")
  .filter(o => o.quantityInEth)
  .map(o => o.quantity / 1000000000000000000);
```

## Some Remarks
- ✅ this does work on pages that have filtering enabled (BUY NOW). [Example](https://opensea.io/collection/cool-cats-nft?search[sortAscending]=true&search[sortBy]=PRICE&search[toggles][0]=BUY_NOW)
- ❌ does not work on the `/collection/{slug}` route without query params. [example](https://opensea.io/collection/cool-cats-nft)
- this new method improves speed because you don't need to scroll
- only the top 32 offers are availible, so if you need more than that you would still need to scroll

Leaving this here for the moment because inside the `__wired__` variable there is a lot of information that I currently cannot make sense of. I think there might be more hidden such that we can maybe also find the tokenId or name in this object. If someone wants to do some digging feel free @Jethro87 @robertistok @Androz2091 .

I implemented a method in the branch `alternative-method-to-get-floor-prices`  but not sure yet whether to replace the old way of scraping that data (through the cards), or leave both methods coexist so the developer can try both functions (not ideal) or implement a fallback machanism (try method 1, if it fails try method2). 
https://github.com/dcts/opensea-scraper/blob/136886477220c821d24aed3f3690f60e2bce625b/src/functions/floorPrice.js#L76

Will leave open for discussion for now :)

**Comment by Jethro87** [comment]
@dcts Nice catch! I just manually tested this on three collections and your solution appears to work. The 32 floor prices corresponded perfectly to the 32 offers available in the `__wired__` variable. 

I think we should "accept" this as a faster/better solution for the time being, but I'm wary of removing the old scrolling method from the package. Who knows if/when OS will remove or change the wired variable. What do you think?

**Comment by dcts** [comment]
Yes totally agree @Jethro87. I am working on a V5 that switches to this new method. I had the same concern as you and thought lets keep both methods, but now I prefere to just drop the "old" method in favor of the new one. This repository should just have the best current working solution, and when it breaks, ideally someone will notice and open an issue. Also the old solution is always usable by reverting to V4.

Also I figured out how to grab the offers currency, so the offers that are in an alternative currency (like SAND or ASH) are also grabbed. Leaving the full solution here in case someone needs it prior to V5 release:
```js
// EXAMPLE TO SCRAPE SANDBOX LAND FLOOR PRICE
// => https://opensea.io/collection/sandbox?search[sortAscending]=true&search[sortBy]=PRICE&search[stringTraits][0][name]=Type&search[stringTraits][0][values][0]=Land&search[toggles][0]=BUY_NOW

// get info about all used currencies
const currencyDict = {};
Object.values(__wired__.records)
  .filter(o => o.__typename === "AssetType")
  .filter(o => o.usdSpotPrice)
  .forEach(currency => {
    currencyDict[currency.id] = {
      id: currency.id,
      symbol: currency.symbol,
      imageUrl: currency.imageUrl,
      usdSpotPrice: currency.usdSpotPrice,
    }
});

// get all floorPrices (all currencies)
const floorPrices = Object.values(__wired__.records)
  .filter(o => o.__typename === "AssetQuantityType")
  .filter(o => o.quantityInEth)
  .map(o => {
    return {
      amount: o.quantity / 1000000000000000000,
      currency: currencyDict[o.asset.__ref].symbol,
    }
});

// get offers
const offers = Object.values(__wired__.records).filter(o => {
  return o.__typename === "AssetType" && o.tokenId;
}).map(o => {
  return {
    tokenName: o.name,
    tokenId: o.tokenId
  };
});

// merge information together:
floorPrices.forEach((floorPrice, indx) => {
  offers[indx].floorPrice = floorPrice;
});
```
