### ISSUE TITLE
Buggy If Multiple Currencies

### ISSUE THREAD

**Issue by ANG3L0** [dcts/opensea-scraper#3]
Some slugs, like lostpoets would have multiple currencies.

The floor for example is at .969 ETH as of this writing.
https://opensea.io/collection/lostpoets

The first listing is selling it for 160 "ASH"

![image](https://user-images.githubusercontent.com/1111860/135652494-15b4ce14-a515-4c42-af13-ce9808ed2f9b.png)

When this scraper scrapes, it returns 160 as floor, instead of .969.

One of 2 ways to handle I think: kill outliers in first few floor listings and take the minimum. Or just convert whatever currency to ETH.

**Comment by dcts** [comment]
Thanks for pointing that out! But I think this repository is no longer needed, becuase Opensea just added support for accurate floor prices in their official API, so we don't need to scrape anymore 🎉🍾

Heres a codesnipped on how to get any floorprice from any project directly from opensea official API, no more scraping needed:
```js
const axios = require("axios");

async function getFloorPrice(slug) {
  try {
    const url = `https://api.opensea.io/collection/${slug}`;
    const response = await axios.get(url);
    return response.data.collection.stats.floor_price;
  } catch(err) {
    console.log(err);
    return undefined;
  }
}

const result = await getFloorPrice("lostpoets");

```

**Comment by dcts** [comment]
Ok nevermind ignore my comment from above, turns out the floor price is still inaccurate with the API. When I checked before it probably was a coincidence that all 4 collections i checked were accurate. When I test it now its not accurate anymore. 

So this issue remains open, thanks for reporting. Will implementing an update that returns a floor price object instead, for example:
```js
const floorPrice = await OpenseaScraper.floorPrice("cool-cats-nft");
// => before it returned a number: e.g. 11.29
// => new return object will look like this:
const targetResultObj = {
  amount: 11.29,
  currency: "ethereum",
} 
```

**Comment by dcts** [comment]
@ANG3L0 I pushed a fix, now it only fetches the price of ETH and ignores all non-ETH items. Hope that is good enough, let me know if it worked so I can close the issue.

**Comment by ANG3L0** [comment]
Yep, works for me. Thanks so much for the quick turnaround!
