### ISSUE TITLE
offers method not working in docker

### ISSUE THREAD

**Issue by mlarcher** [dcts/opensea-scraper#32]
it crashes on https://github.com/dcts/opensea-scraper/blob/main/src/functions/offers.js#L101 because html does not contain `window.__wired__=`
Proabably this is because the page contains `This website is using a security service to protect itself from online attacks.`. I'm providing a custom puppeteer instance...

**Comment by dcts** [comment]
If anyone encounters this error, it is because you most likely need to use [stealth plugin](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth) for puppeteer. 

See #33 

Thanks @mlarcher for pointing this out!
