### ISSUE TITLE
question

### ISSUE THREAD

**Issue by venusbin** [dcts/opensea-scraper#42]
Is there a way to apply opensea's filters?

ex) https://opensea.io/collection/boredapeyachtclub?search[sortBy]=PRICE&search[sortAscending]=true&search[stringTraits][0][name]=Background&search[stringTraits][0][values][0]=Purple

**Comment by dcts** [comment]
Yes, you can do:
```js
const urlWithFilters = "https://opensea.io/collection/boredapeyachtclub?search[sortBy]=PRICE&search[sortAscending]=true&search[stringTraits][0][name]=Background&search[stringTraits][0][values][0]=Purple";
const res = await OpenseaScraper.offersByUrl(urlWithFilters, options);
```
