### ISSUE TITLE
Reading from Activity page

### ISSUE THREAD

**Issue by kris-ow** [dcts/opensea-scraper#46]
Would you consider adding a feature of reading from an activity page (sales/listings)? e.g. https://opensea.io/collection/sandbox?tab=activity&search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED

**Comment by dcts** [comment]
I think if you need the latest sales data you can get it from Opensea API directly. No scraping needed. Read more here:
https://docs.opensea.io/reference/event-object

![Bildschirmfoto vom 2022-04-02 02-54-10](https://user-images.githubusercontent.com/44790691/161357762-c7281a6a-1856-45e1-b1e5-67c949dbf805.png)
