### ISSUE TITLE
[BUG] Missing price in result

### ISSUE THREAD

**Issue by githuilan** [dcts/opensea-scraper#60]
The result cannot get prices anymore

![image](https://user-images.githubusercontent.com/86963227/178765213-09bca3a4-19a9-426b-94e8-4630d779f2b5.png)

**Comment by dcts** [comment]
thanks for reporting. Same bug as #61 . Working on it.

**Comment by dcts** [comment]
@githuilan a fix for this was created. To adapt please use version `6.5.2`:
```
npm install opensea-scraper@6.5.2
```

or alternatively if you have it already installed upgrade to latest version
```
npm upgrade
```

Let me know if it worked!
