### ISSUE TITLE
  offersByScrolling() and  offersByScrollingByUrl() does not work

### ISSUE THREAD

**Issue by MetalGear-cmd** [dcts/opensea-scraper#63]
Hey everyone so I have been trying to scrape some page from Opensea. And I have used the  offersByScrollingByUrl() but I was unsuccessful. 
When I use these methods  offersByScrollingByUrl() even though I provide the resultSize it stop once it reaches the bottom of page. 
and once it reaches the bottom it returns empty resuly.
{ offers: [], stats: { totalOffers: undefined } }

my code:
`const options = {
  debug: false,
  logs: true,
  sort: false,
  additionalWait: 0,
  browserInstance: undefined,
};

(async () => {
    try {
      let resultSize=1
          const urlWithFilters = 'https://opensea.io/collection/wilderness-to-blockchain-editions?search[sortAscending]=false&search[sortBy]=LAST_SALE_DATE&search[toggles][0]=BUY_NOW';
          const res = await OpenseaScraper.offersByScrollingByUrl(urlWithFilters,resultSize, options);
          OpenseaScraper.
        //   const res = await OpenseaScraper.offersByUrl(urlWithFilters,options)
          console.log(res);
    } catch (err) {
      console.log(err);
    }
  })();`

Any help??
thanks
using the latest v 6.5.2.

**Comment by dcts** [comment]
@MetalGear-cmd sorry for the late reply, `offersByScrolling` is not working anymore (unfortunately), see issue #36 and [disclaimer](https://github.com/dcts/opensea-scraper/blob/ab3f02aca0dd6ec33397d32eaf3ab2d8ed1ea8ca/README.md?plain=1#L78-L79) in the readme file. Closing as duplicate.
