### ISSUE TITLE
How to scrape more than top 100?

### ISSUE THREAD

**Issue by nathan1505** [dcts/opensea-scraper#64]
Is there a way to scrape the ranking outside of the top 100 from the latest version?

**Comment by dcts** [comment]
Hi, sorry for the late reply, somehow missed this one. 
Curently there is no way to scrape beyond 100 collections on the rankings page.

**Comment by dcts** [comment]
Hi, sorry for the late reply, somehow missed this one. 
Curently there is no way to scrape beyond 100 collections on the rankings page.
