### ISSUE TITLE
floorprice is null

### ISSUE THREAD

**Issue by waheedshabeer** [dcts/opensea-scraper#65]
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/63425832/202286584-3c41c50d-2605-4d7c-b6a3-c53d52fd0a3c.png">

**Comment by dcts** [comment]
Can you share your code that produced this output?

**Comment by waheedshabeer** [comment]
ranking = await OpenseaScraper.rankings("24h");

**Comment by dcts** [comment]
should be fixed, can you upgrade to v6.6.0 and test it? @waheedshabeer

**Comment by waheedshabeer** [comment]
Okay

**Comment by waheedshabeer** [comment]
> should be fixed, can you upgrade to v6.6.0 and test it? @waheedshabeer
Working fine now after using version 6.6.0
@dcts 

Version     "opensea-scraper": "6.6.0",

**Comment by waheedshabeer** [comment]
Thank you @dcts

**Comment by dcts** [comment]
awesome! Thanks for reporting! :)
