### ISSUE TITLE
Can't obtain any information from opensea due to cloudflare

### ISSUE THREAD

**Issue by kaiqiangh** [dcts/opensea-scraper#68]
I've added addtionalWait (up to 1 minute) to get html.content(), but it seems that opensea blocks me from it. 

Note, it works when getting nft information from opensea testnet. Any tips?

![image](https://user-images.githubusercontent.com/9014062/215757196-ab40cf2e-3e3f-4084-a126-254b1c059b1e.png)

**Comment by dcts** [comment]
this is a cloudflare issue, unfortunately I don't know how to solve, other than changing your environment. Launching the scraper from a cloud server like gcloud or firebase functions or heroku usually doesn't work. Using a private machine or using proxy services (expensive) should work though. 

Good luck, please share if you are able to fix it.

**Comment by kaiqiangh** [comment]
Hi @dcts , Thanks for your reply. I just tried that AWS works for this part
